import { AIAction, ActionType } from '@/types/action';

const actionTypes: ActionType[] = ['email', 'api_call', 'database', 'notification', 'file_operation', 'integration'];

const descriptions: Record<ActionType, string[]> = {
  email: [
    'Send welcome email to new user',
    'Send password reset notification',
    'Send weekly digest to subscribers',
    'Notify client about order status',
    'Send invoice reminder to customer',
  ],
  api_call: [
    'Sync user data with CRM',
    'Fetch latest pricing from vendor API',
    'Update inventory levels via API',
    'Send webhook to payment processor',
    'Refresh OAuth tokens for integration',
  ],
  database: [
    'Archive inactive user accounts',
    'Migrate legacy data format',
    'Clean up expired sessions',
    'Update user preferences schema',
    'Backup critical transaction logs',
  ],
  notification: [
    'Push notification: New message received',
    'Alert admin about security event',
    'Remind user about pending task',
    'Notify team about deployment status',
    'Send low inventory warning',
  ],
  file_operation: [
    'Generate monthly sales report',
    'Export user data for compliance',
    'Compress and archive old logs',
    'Process uploaded documents',
    'Generate PDF invoice',
  ],
  integration: [
    'Sync contacts with Salesforce',
    'Update Slack channel with metrics',
    'Post status update to Jira',
    'Connect new Stripe subscription',
    'Sync calendar with Google Workspace',
  ],
};

const entities: Record<ActionType, string[]> = {
  email: ['EmailService', 'NotificationQueue', 'UserMailer'],
  api_call: ['ExternalAPI', 'WebhookHandler', 'APIGateway'],
  database: ['PostgresDB', 'DataMigrator', 'SessionStore'],
  notification: ['PushService', 'AlertManager', 'NotificationHub'],
  file_operation: ['FileProcessor', 'ReportGenerator', 'StorageService'],
  integration: ['SalesforceSync', 'SlackIntegration', 'GoogleWorkspace'],
};

function randomDate(start: Date, end: Date): Date {
  return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
}

function generateMockAction(id: number): AIAction {
  const actionType = actionTypes[Math.floor(Math.random() * actionTypes.length)];
  const descList = descriptions[actionType];
  const entityList = entities[actionType];
  
  const statusRoll = Math.random();
  const status = statusRoll < 0.6 ? 'pending' : statusRoll < 0.8 ? 'approved' : 'rejected';

  return {
    id: `action-${id.toString().padStart(4, '0')}`,
    description: descList[Math.floor(Math.random() * descList.length)],
    entity: entityList[Math.floor(Math.random() * entityList.length)],
    actionType,
    timestamp: randomDate(new Date(Date.now() - 7 * 24 * 60 * 60 * 1000), new Date()),
    status,
    metadata: {
      confidence: Math.round((0.7 + Math.random() * 0.3) * 100) / 100,
      source: 'AI Agent v2.3',
      details: `Generated by autonomous workflow. Action ID: ${id}`,
      relatedEntities: Math.random() > 0.5 
        ? [entityList[Math.floor(Math.random() * entityList.length)]]
        : undefined,
    },
  };
}

export const mockActions: AIAction[] = Array.from({ length: 50 }, (_, i) => generateMockAction(i + 1));
